<h4>Plots of patchwork.CG.plot()</h4>

Here is an example plot of chromosome 1, 70% tumor cells, generated from HCC1187.<br />
After running patchwork.CG.plot() you should have 24 of these in your working directory, one for
each chromosome.<br /><br />

For information regarding allelic imbalance and coverage click <a href="AI_Cov.php" target="_blank" style="text-decoration:none;">here</a>.

<h5>Top part of the plot</h5>

The clusters in the plot display regions of certain allelic constitution and copy number.
The copy number increases along the Coverage axis while paternal/maternal allele ratio
becomes less balanced along the Allelic Imbalance axis. We can use this information to determine the clusters probable copy number
and allele content.<br /><br />

The chromosome in question is colored against a background of the complete genome in grey.
A colored circles gradient and size correlate with its segments position and size on the
 chromosome. Colors of segments match in regard to all three parts of the plot.
 The circles are semi-transparent so a darker hue, both for colored and grey,
 indicate greater amount of genomic content in that region.<br /><br />

We know that each cluster has a certain copy number and allele content and we know that the average
copy number of the genome in question is at position 1 on the Coverage axis.
The far left cluster is the deletions, copy number 1. After copy number 1 we
see two clusters, albeit the lower one does not have much content. They are most likely
the two allelic states of copy number 2.
Continuing with this reasoning the next set of clusters is copy number 3, etc.

This arrangement of the genome is easier to see from one of the plots generated by
patchwork.CG.copynumbers(), or in our section above on allelic imbalance, however before using
 that function you will need to be able to determine the constitution of the tumor
  genome as it is used as input arguments for patchwork.CG.copynumbers()!

<img id="fig2cg" src="css/img/70_HCC1187__KaCh_chr1.png" alt="Results example patchwork.CG.plot"
 title="Figure 2 patchworkCG"
 style="width:880px"><br /><br />

<h5>Middle part of the plot</h5>

The chromosome in questions coverage plotted against the position on the chromosome.
Note how the segments colors match the Top circles and Bottom segments.

<h5>Bottom part of the plot</h5>

The chromosome in questions allelic imbalance plotted against the
position on the chromosome.

<br /><br /><h4>Plots of patchwork.CG.copynumbers()</h4>

This plot, arbitrarily named "check", is not chromosome specific and shows
the complete tumor genome with assigned tags for copy number and allele content,
much like the <a href="css/img/Allelic_plot.png" target="_blank" style="text-decoration:none;">explanatory picture</a>
seen previously but with text describing the copy numbers and allele ratios of the segments
rather than purple and green bars.

<img id="fig3cg" src="css/img/70_HCC1187_check.png" alt="Results example patchworkCG check"
 title="Figure 3 patchworkCG"
 style="width:880px"><br /><br />

<b>1m0</b> is copy number 1, homozygous. <br />
<b>2m1</b> is copy number 2, heterozygous. <br />
<b>2m0</b> is copy number 2, homozygous. <br />
<b>3m1</b> is copy number 3, heterozygous. <br />
<b>3m0</b> is copy number 3, homozygous. <br />
And so on. <br /><br />

The other chromosomal plots generated from patchwork.CG.copynumbers() are the same as
the ones generated by patchwork.CG.plot() but with one extra part of the plot. <br />

<img id="fig4cg" src="css/img/70_HCC1187_copynumbers_KaChCN_chr1.png" alt="Results example patchwork.CG.copynumbers"
 title="Figure 4 patchworkCG"
 style="width:880px"><br /><br />

In the part of the plot seen second from the top we see the total copy number, colored,
and minor copy number, grey, of a segment. If a segments total copy number is 4 and 
minor copy number is 2 then that segment of the chromosome has 2 paternal and 2 maternal
copies.<br />
Another example; if a segments total copy number is 3 and minor copy number is 0 then
that segment of the chromosome has 3 paternal OR 3 maternal copies.

<!-- Uncomment when article is out.
<br /><br />For more background information please read our submitted article! -->

<br /><br /><div style="text-align:center;"><a href="#top" style="text-decoration:none;">Top</a></div>






















